services:
  frontend:
    container_name: "ATOMSKILLS_FRONTEND"
    build:
      context: ../frontend
      dockerfile: dockerfile
    volumes:
      - ./front_build:/var/www/build
  
  backend:
    container_name: "ATOMSKILLS_BACKEND"
    restart: always
    build: 
      context: ../backend
      dockerfile: dockerfile
    ports:
      - "8082:8082"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
  

  mongo:
    container_name: "ATOMSKILLS_DB"
    image: mongo
    volumes:
      - ./mongo_data:/data/mongo
    ports:
      - "27017:27017"
    


  nginx:
    image: nginx
    restart: always
    depends_on:
      - frontend
    volumes:
      - ./front_build:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8080:80"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:

      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false